### ISSUE TITLE
Lots of information missing required to build this board

### ISSUE THREAD

**Issue by haldean** [sparkfun/ZX_Gesture_Sensor_SMD#18]
Hi there! Both the firmware for the PIC controller on the board and the source for the ZX arduino library are missing from this repository, which means that there's not enough information to make one of these. Were these just accidentally excluded? It looks like there's directories for them to go in, there's just nothing in the Firmware or Software folders.

**Comment by loricrotser** [comment]
Hi! 

Since this is a project for the arduino, we don't have the firmware for the PIC controller uploaded here. The header and cpp are available for modification, and it may be that someone has done this already. The [forums](https://forum.sparkfun.com/) may have more information on this. 

The libraries are housed in their own repo - I have updated the pull link in the readme here. The libraries can also be downloaded from the [hookup guide](https://learn.sparkfun.com/tutorials/zx-distance-and-gesture-sensor-smd-hookup-guide). 

Hope this helps!

**Comment by ShawnHymel** [comment]
@haldean If you are referring to the firmware on the PIC that's on the ZX board itself, that firmware is not open source. The ZX sensor was created as a collaboration between SparkFun and [XYZ Interactive](http://www.xyzinteractive.com/gesturesense-gesture_sensor_supplier/). We are able to open source the hardware, but XYZ still owns the intellectual property on the firmware. You are welcome to reach out to them if you would like to produce your own sensors.

**Comment by haldean** [comment]
@ShawnHymel @loricrotser Then I'd request you remove the statement that this product is open source from the README. If the software it runs isn't open source, then the product isn't open source.
